import Head from "next/head";
import Image from "next/image";
import Button from "@/components/Button";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  if (typeof window === "object") {
    // 这个是在客户端 client
    console.log("client");
    console.log(process.env.NEXT_PUBLIC_NAME);
    // console.log(process.server); nextjs 不支持
  } else {
    console.log("server");
    console.log(process.env.NAME);
    console.log(process.env.PORT);
    console.log(process.env.TEXT);
  }
  const Router = useRouter();

  useEffect(() => {
    // 监听路由切换改变
    Router.events.on("routeChangeStart", (e) => {
      console.log("routeChangeStart=》", e);
    });
    Router.events.on("routeChangeComplete", (e) => {
      console.log("routeChangeComplete=》", e);
    });
  }, []);

  return (
    <>
      <Head>
        <title>777 Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="textColor">hello world</div>
      {/* <Image
        height={122}
        alt=""
        width={182}
        priority // priority 预加载， fill 填充 这个需要有一个父元素在父元素上面加上相等定位
        src={
          "https://gimg3.baidu.com/search/src=http%3A%2F%2Fpics5.baidu.com%2Ffeed%2Fcb8065380cd79123010e44eaef53f489b3b78031.jpeg%40f_auto%3Ftoken%3Db4d27d3689e3787eb3cf5ee7bcb2d498&refer=http%3A%2F%2Fwww.baidu.com&app=2021&size=f360,240&n=0&g=0n&q=75&fmt=auto?sec=1675789200&t=93ee2d6565fac72d25964ebb0a272f73"
        }
      /> */}
      <Button />

      <Link href={"/about"}>
        <button>about</button>
      </Link>
      <Link
        href={{
          pathname: "/cart",
          query: {
            count: 10,
          },
        }}
      >
        <button>cart</button>
      </Link>
      {/* as 是个url路径取一个别名  replace 替换当前页面 返回的时候就不会返回到上一个页面*/}
      <Link href={"/profile"} as="profile_v2" replace>
        <button>profile</button>
      </Link>

      {/* 编程式导航 */}
      <button
        onClick={() => {
          Router.push("/profile");
        }}
      >
        profile 编程导航
      </button>
    </>
  );
}
